- RedTooth (Mobile)/src/main.js
- RedTooth (Mobile)/src/navigationBar.js
- RedTooth (Mobile)/src/scrollingexample.js
> added margin to make navbar viewable

- RedTooth (Mobile)/src/addClothingModal.js
- RedTooth (Mobile)/src/main.js
- RedTooth (Mobile)/src/navigationBar.js
Associates navigation bar's add button with "Add Clothing" modal. Yis.
> Added modal when adding clothing.

- RedTooth (Mobile)/src/addClothingModal.js
> Aesthetic fixes.

- RedTooth (Mobile)/src/addCategory.js
- RedTooth (Mobile)/src/category.js
- RedTooth (Mobile)/src/main.js
- RedTooth (Mobile)/src/navigationBar.js
- RedTooth (Mobile)/src/scrollingexample.js
placeholder view implementation
> Category object

- RedTooth (Mobile)/src/addClothingModal.js
- RedTooth (Mobile)/src/navigationBar.js
Modal now clears whenever user hits "add" button.
> Added clearing for modal.

- RedTooth (Mobile)/src/addCategory.js
- RedTooth (Mobile)/src/category.js
- RedTooth (Mobile)/src/categoryScreen.js
- RedTooth (Mobile)/src/main.js
categories now displaying in scrollView. Additionally, categories array moved to categoriesScreen.js.
Please review, @nandasachal
> Adding categories

- RedTooth (Mobile)/src/addCategory.js
- RedTooth (Mobile)/src/addClothingModal.js
- RedTooth (Mobile)/src/categoryScreen.js
- RedTooth (Mobile)/src/clothingScreen.js
- RedTooth (Mobile)/src/navigationBar.js
What description says.
Reviewer: @ghear @helinda
> Navbar is now always on top.

- RedTooth (Mobile)/src/addCategory.js
- RedTooth (Mobile)/src/category.js
- RedTooth (Mobile)/src/categoryScreen.js
- RedTooth (Mobile)/src/main.js
categories displaying with COLOR!
@DarryQueen
> Add categories

- RedTooth (Mobile)/src/addCategoryToClothing.js
- RedTooth (Mobile)/src/addClothingModal.js
- RedTooth (Mobile)/src/category.js
this also adds the new clothing to each of the selected categories
> you can now add categories when adding clothing

- RedTooth (Mobile)/src/addClothingModal.js
- RedTooth (Mobile)/src/hangerManager.js
- RedTooth (Mobile)/src/main.js
- RedTooth (Mobile)/src/navigationBar.js
- Redtooth (Device)/src/main.js
Syncing and adding clothing now works.
> Syncing now works.

- RedTooth (Mobile)/src/categoryDetailView.js
- RedTooth (Mobile)/src/categoryDetailViewNavBar.js
- RedTooth (Mobile)/src/clothing.js
> Lighting shit up.

- RedTooth (Mobile)/src/addClothingModal.js
- RedTooth (Mobile)/src/categoryScreen.js
- RedTooth (Mobile)/src/clothing.js
- RedTooth (Mobile)/src/hangerManager.js
Self-explanatory.
Reviewer: @ghear @nandasachal
> Added id to clothing things.

- RedTooth (Mobile)/src/addCategory.js
- RedTooth (Mobile)/src/addCategoryToClothing.js
- RedTooth (Mobile)/src/addClothingModal.js
- RedTooth (Mobile)/src/addClothingToCategory.js
- RedTooth (Mobile)/src/categoryDetailView.js
- RedTooth (Mobile)/src/clothing.js
- RedTooth (Mobile)/src/clothingScreen.js
- RedTooth (Mobile)/src/main.js
> Hangers stuff.

- RedTooth (Mobile)/src/hangerManager.js
- Redtooth (Device)/src/main.js
Added method for device to dim all hangers.
> Added dimAll method.

- RedTooth (Mobile)/src/categoryDetailView.js
- RedTooth (Mobile)/src/categoryScreen.js
lighting up
Review Request: @DarryQueen
> properly lighting from category detail view

- RedTooth (Mobile)/src/categoryDetailViewNavBar.js
- RedTooth (Mobile)/src/hangerManager.js
- Redtooth (Device)/src/main.js
dimming all objects
@DarryQueen
> dimming all

- Redtooth (Device)/simulator/potentiometers.js
> changed device labels

- RedTooth (Mobile)/src/hangerManager.js
- RedTooth (Mobile)/src/navigationBar.js
> Removed add button and changed sync button.

- RedTooth (Mobile)/src/navigationBar.js
> Re-added add button on categories page.

- RedTooth (Mobile)/src/addCategory.js
- RedTooth (Mobile)/src/addCategoryToClothing.js
- RedTooth (Mobile)/src/addClothingModal.js
- RedTooth (Mobile)/src/addClothingToCategory.js
- RedTooth (Mobile)/src/addClothingToCategoryNavBar.js
- RedTooth (Mobile)/src/categoryDetailView.js
- RedTooth (Mobile)/src/categoryDetailViewNavBar.js
- RedTooth (Mobile)/src/categoryScreen.js
- RedTooth (Mobile)/src/clothingScreen.js
- RedTooth (Mobile)/src/hangerManager.js
- RedTooth (Mobile)/src/main.js
- RedTooth (Mobile)/src/navigationBar.js
> Restructured dependencies.

- RedTooth (Mobile)/src/categoryDetailView.js
- RedTooth (Mobile)/src/categoryDetailViewNavBar.js
- RedTooth (Mobile)/src/categoryScreen.js
- RedTooth (Mobile)/src/clothing.js
- RedTooth (Mobile)/src/clothingScreen.js
- RedTooth (Mobile)/src/editCategory.js
- RedTooth (Mobile)/src/editClothingInCategory.js
- RedTooth (Mobile)/src/editClothingInCategoryNavBar.js
- RedTooth (Mobile)/src/main.js
- RedTooth (Mobile)/src/navigationBar.js
> Categories work

- RedTooth (Mobile)/src/addClothingModal.js
- RedTooth (Mobile)/src/hangerManager.js
- RedTooth (Mobile)/src/navigationBar.js
> Fix for update on category screen.
